# Generated by Django 5.1.3 on 2024-12-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CORRECTIVO', 'Correctivo'), ('PREVENTIVO', 'Preventivo'), ('ADAPTATIVO', 'Adaptativo'), ('PERFECTIVO', 'Perfectivo')], max_length=20, verbose_name='Tipo de mantenimiento')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('modulo_afectado', models.CharField(max_length=100, verbose_name='Módulo afectado')),
                ('acciones_realizadas', models.TextField(verbose_name='Acciones realizadas')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['-fecha'],
            },
        ),
    ]
