# Generated by Django 5.1.3 on 2024-12-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('level', models.CharField(choices=[('success', 'Éxito'), ('error', 'Error'), ('warning', 'Advertencia'), ('info', 'Información')], default='info', max_length=20, verbose_name='Nivel')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('viewed', models.BooleanField(default=False, verbose_name='Visto')),
            ],
            options={
                'verbose_name': 'Mensaje del Sistema',
                'verbose_name_plural': 'Mensajes del Sistema',
                'ordering': ['-timestamp'],
            },
        ),
    ]
