# Generated by Django 5.1.3 on 2024-12-15 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmessage',
            name='app',
            field=models.CharField(choices=[('inventario', 'Inventario'), ('ventas', 'Ventas'), ('compras', 'Compras'), ('usuario', 'Usuario'), ('sistema', 'Sistema')], default='sistema', max_length=20, verbose_name='Aplicación'),
        ),
        migrations.AddField(
            model_name='systemmessage',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemmessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
